name: "Build and Push Docker Images"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docker/**'

jobs:
  build-and-push:
    name: "Build and Push Docker Images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [php-cli]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Set Up Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@a0c73a10bb6782f082cd6714666c87911e4fc7d3 # master
        with:
          install: true

      - name: Log In to Github Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./docker/${{ matrix.image }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest
          platforms: linux/amd64,linux/arm64
