name: Check GitHub Actions

on:
  push:
    branches: ["main"]
    paths:
      - ".github/**/*.yml"
      - ".github/dependabot.yml" # `**` matches any character, so the glob above requires a nested directory.
  pull_request:
    paths:
      - ".github/**/*.yml"
      - ".github/dependabot.yml" # `**` matches any character, so the glob above requires a nested directory.

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Check .yml files
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Download actionlint
        id: download-actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      # we prefer individual redirects over { cmd1; cmd2; } >> file, @see https://www.shellcheck.net/wiki/SC2129
      - name: Check workflow files
        run: ${STEPS_DOWNLOAD_ACTIONLINT_OUTPUTS_EXECUTABLE} -color .github/workflows/*.yml
        shell: bash
        env:
          STEPS_DOWNLOAD_ACTIONLINT_OUTPUTS_EXECUTABLE: ${{ steps.download-actionlint.outputs.executable }}

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          advanced-security: false # We don't currently pay for https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security
          config: .github/zizmor.yml
          persona: pedantic
